import { useQuery } from "@tanstack/react-query";
import { useServerFn } from "@tanstack/react-start";
import { Link, createFileRoute } from "@tanstack/react-router";
import { ArrowLeft, CalendarClock, CircleDollarSign, FileText, MessageSquareText, PhoneCall, Sparkles, UserRound } from "lucide-react";
import { TopBar } from "@/components/app-sidebar";
import { Button } from "@/components/ui/button";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { getCrmContactRecord } from "@/lib/crm-foundation.functions";
import { cn } from "@/lib/utils";

export const Route = createFileRoute("/_authenticated/sales/contacts/$id")({ component: SalesContactRecord });

type RecordData = Awaited<ReturnType<typeof getCrmContactRecord>>;

type TimelineItem = { id: string; timestamp: string; type: "crm" | "note" | "event" | "call" | "message"; title: string; body?: string | null; tone?: string };

function currency(cents: number | null | undefined, code = "USD") {
  return new Intl.NumberFormat("en-US", { style: "currency", currency: code, maximumFractionDigits: 0 }).format((cents ?? 0) / 100);
}
function dateTime(value?: string | null) { return value ? new Date(value).toLocaleString(undefined, { month: "short", day: "numeric", year: "numeric", hour: "numeric", minute: "2-digit" }) : "No timestamp"; }

function SalesContactRecord() {
  const { id } = Route.useParams();
  const getRecord = useServerFn(getCrmContactRecord);
  const recordQuery = useQuery({ queryKey: ["sales-crm-contact", id], queryFn: () => getRecord({ data: { id } }) });
  const record = recordQuery.data;

  if (recordQuery.isLoading) return <><TopBar title="Sales CRM" subtitle="Contact workspace" /><div className="space-y-4 p-6"><div className="h-10 w-32 animate-pulse rounded bg-muted" /><div className="h-[560px] animate-pulse rounded-xl bg-muted/40" /></div></>;
  if (recordQuery.isError || !record) return <><TopBar title="Sales CRM" subtitle="Contact workspace" /><div className="p-6"><Link to="/sales" className="text-sm text-accent hover:underline">Back to Sales CRM</Link><div className="mt-5 rounded-xl border border-destructive/40 bg-destructive/5 p-6 text-sm">This CRM record is unavailable. The record may not belong to your current workspace.</div></div></>;

  const timeline = buildTimeline(record as RecordData);
  const contact = record.contact;
  return (
    <>
      <TopBar title={contact.display_name} subtitle="Sales CRM record workspace" />
      <main className="mx-auto max-w-[1800px] space-y-4 p-4 sm:p-6">
        <div className="flex flex-wrap items-center justify-between gap-3">
          <Button variant="ghost" size="sm" asChild><Link to="/sales"><ArrowLeft className="h-3.5 w-3.5" />Sales CRM</Link></Button>
          <span className={cn("rounded px-2 py-1 text-3xs font-semibold uppercase tracking-wide", contact.record_source === "legacy_lead" ? "bg-muted text-muted-foreground" : "bg-accent/15 text-accent")}>{contact.record_source === "legacy_lead" ? "Preserved legacy lead" : "CRM contact"}</span>
        </div>
        <div className="grid gap-4 xl:grid-cols-[280px_minmax(0,1fr)_320px]">
          <aside className="space-y-4"><section className="rounded-xl border border-border/80 bg-card p-4"><div className="grid h-12 w-12 place-items-center rounded-full bg-accent/10 text-accent"><UserRound className="h-5 w-5" /></div><h1 className="mt-3 text-xl font-semibold tracking-tight">{contact.display_name}</h1><p className="mt-1 text-xs capitalize text-muted-foreground">{contact.lifecycle_status.replaceAll("_", " ")}</p><dl className="mt-5 space-y-3 text-sm"><Info label="Email" value={contact.primary_email} /><Info label="Phone" value={contact.primary_phone} /><Info label="Handle" value={contact.social_handle ? `@${contact.social_handle.replace(/^@/, "")}` : null} /><Info label="Source" value={contact.source} /><Info label="Created" value={dateTime(contact.created_at)} /></dl></section>{record.legacy?.lead && <LegacyContext legacy={record.legacy.lead as Record<string, unknown>} />}</aside>
          <section className="min-w-0 rounded-xl border border-border/80 bg-card"><Tabs defaultValue="timeline"><div className="border-b border-border/70 px-4 pt-4"><TabsList className="bg-muted/40"><TabsTrigger value="timeline">Timeline</TabsTrigger><TabsTrigger value="communications">Messages</TabsTrigger><TabsTrigger value="legacy">Legacy context</TabsTrigger></TabsList></div><TabsContent value="timeline" className="m-0 p-4"><div className="mb-4"><h2 className="text-sm font-semibold">Relationship timeline</h2><p className="mt-1 text-xs text-muted-foreground">Native CRM activity is shown alongside preserved lead notes, events, and call history. No historical data is copied or discarded.</p></div><Timeline items={timeline} /></TabsContent><TabsContent value="communications" className="m-0 p-4"><ConversationList conversations={(record.legacy?.conversations ?? []) as Array<Record<string, unknown>>} /></TabsContent><TabsContent value="legacy" className="m-0 p-4"><LegacyData legacy={record.legacy} /></TabsContent></Tabs></section>
          <aside className="space-y-4"><OpportunityList opportunities={record.opportunities as Array<Record<string, unknown>>} /><TaskList tasks={record.tasks as Array<Record<string, unknown>>} /></aside>
        </div>
      </main>
    </>
  );
}

function Info({ label, value }: { label: string; value?: string | null }) { return <div><dt className="text-2xs font-medium uppercase tracking-wide text-muted-foreground">{label}</dt><dd className="mt-1 break-words text-sm">{value || "—"}</dd></div>; }

function LegacyContext({ legacy }: { legacy: Record<string, unknown> }) { return <section className="rounded-xl border border-border/80 bg-card p-4"><h2 className="text-sm font-semibold">Legacy sales context</h2><dl className="mt-3 grid grid-cols-2 gap-3 text-xs"><Info label="Priority" value={String(legacy.priority ?? "—")} /><Info label="Stage" value={String(legacy.pipeline_stage ?? "—")} /><Info label="Intent" value={legacy.intent_score == null ? "—" : String(legacy.intent_score)} /><Info label="Close probability" value={legacy.estimated_close_probability == null ? "—" : `${legacy.estimated_close_probability}%`} /></dl>{legacy.qualification_notes ? <div className="mt-4 border-t border-border pt-3"><div className="text-2xs font-medium uppercase tracking-wide text-muted-foreground">Qualification</div><p className="mt-1.5 text-xs leading-5 text-muted-foreground">{String(legacy.qualification_notes)}</p></div> : null}</section>; }

function Timeline({ items }: { items: TimelineItem[] }) { return <div className="relative space-y-0 before:absolute before:bottom-4 before:left-[13px] before:top-4 before:w-px before:bg-border">{items.map((item) => <div key={item.id} className="relative flex gap-3 py-3"><span className={cn("z-10 mt-0.5 grid h-7 w-7 shrink-0 place-items-center rounded-full border border-border bg-card", item.tone ?? "text-accent")}><TimelineIcon type={item.type} /></span><div className="min-w-0 flex-1 rounded-lg border border-border/70 bg-muted/15 p-3"><div className="flex flex-wrap items-start justify-between gap-2"><div className="text-sm font-medium">{item.title}</div><time className="text-2xs text-muted-foreground">{dateTime(item.timestamp)}</time></div>{item.body ? <p className="mt-1.5 whitespace-pre-wrap text-xs leading-5 text-muted-foreground">{item.body}</p> : null}</div></div>)}{!items.length && <div className="rounded-lg border border-dashed border-border p-8 text-center text-sm text-muted-foreground">No activity is available for this record yet.</div>}</div>; }
function TimelineIcon({ type }: { type: TimelineItem["type"] }) { if (type === "call") return <PhoneCall className="h-3.5 w-3.5" />; if (type === "note") return <FileText className="h-3.5 w-3.5" />; if (type === "message") return <MessageSquareText className="h-3.5 w-3.5" />; if (type === "crm") return <Sparkles className="h-3.5 w-3.5" />; return <CalendarClock className="h-3.5 w-3.5" />; }

function OpportunityList({ opportunities }: { opportunities: Array<Record<string, unknown>> }) { return <section className="rounded-xl border border-border/80 bg-card"><div className="border-b border-border/70 px-4 py-3"><h2 className="text-sm font-semibold">Opportunities</h2></div><div className="divide-y divide-border/60">{opportunities.map((opportunity) => <div key={String(opportunity.id)} className="p-4"><div className="text-sm font-medium">{String(opportunity.name)}</div><div className="mt-1 flex items-center gap-1.5 text-xs text-muted-foreground"><CircleDollarSign className="h-3.5 w-3.5" />{currency(Number(opportunity.amount_cents ?? 0), String(opportunity.currency ?? "USD"))}</div><div className="mt-2 flex items-center justify-between text-2xs text-muted-foreground"><span className="capitalize">{String(opportunity.status)}</span><span>{opportunity.expected_close_date ? `Close ${new Date(String(opportunity.expected_close_date)).toLocaleDateString()}` : "No close date"}</span></div></div>)}{!opportunities.length && <div className="p-5 text-center text-xs text-muted-foreground">No CRM opportunities yet.</div>}</div></section>; }
function TaskList({ tasks }: { tasks: Array<Record<string, unknown>> }) { return <section className="rounded-xl border border-border/80 bg-card"><div className="border-b border-border/70 px-4 py-3"><h2 className="text-sm font-semibold">Open tasks</h2></div><div className="divide-y divide-border/60">{tasks.map((task) => <div key={String(task.id)} className="p-4"><div className="text-sm font-medium">{String(task.title)}</div>{task.description ? <p className="mt-1 text-xs leading-5 text-muted-foreground">{String(task.description)}</p> : null}<div className="mt-2 flex items-center justify-between text-2xs text-muted-foreground"><span className="uppercase">{String(task.priority)}</span><span>{dateTime(task.due_at as string | null)}</span></div></div>)}{!tasks.length && <div className="p-5 text-center text-xs text-muted-foreground">No open tasks for this record.</div>}</div></section>; }

function ConversationList({ conversations }: { conversations: Array<Record<string, unknown>> }) { return <div className="space-y-3">{conversations.map((conversation) => <section key={String(conversation.id)} className="rounded-lg border border-border/80"><div className="flex items-center justify-between border-b border-border/70 px-3 py-2"><span className="text-xs font-semibold capitalize">{String(conversation.channel ?? "message").replaceAll("_", " ")}</span><span className="text-2xs text-muted-foreground">{String(conversation.status ?? "open")}</span></div><div className="space-y-2 p-3">{((conversation.messages ?? []) as Array<Record<string, unknown>>).map((message) => <div key={String(message.id)} className={cn("max-w-[88%] rounded-lg px-3 py-2 text-xs", message.direction === "outbound" ? "ml-auto bg-accent/15" : "bg-muted/50")}><div className="mb-1 text-3xs uppercase tracking-wide text-muted-foreground">{String(message.direction ?? "message")}</div><div className="whitespace-pre-wrap">{String(message.body ?? "")}</div><div className="mt-1 text-3xs text-muted-foreground">{dateTime(message.sent_at as string | null)}</div></div>)}{!((conversation.messages ?? []) as unknown[]).length && <div className="text-xs text-muted-foreground">No messages were retained in this conversation.</div>}</div></section>)}{!conversations.length && <div className="rounded-lg border border-dashed border-border p-8 text-center text-sm text-muted-foreground">No preserved conversations are connected to this record.</div>}</div>; }

function LegacyData({ legacy }: { legacy: RecordData["legacy"] }) { if (!legacy) return <div className="rounded-lg border border-dashed border-border p-8 text-center text-sm text-muted-foreground">This is a native CRM contact with no linked legacy lead.</div>; const entries = Object.entries((legacy.lead ?? {}) as Record<string, unknown>).filter(([key, value]) => value !== null && value !== undefined && value !== "" && !["id", "application_data"].includes(key)); return <div className="space-y-5"><div><h2 className="text-sm font-semibold">Preserved lead attributes</h2><div className="mt-3 grid gap-2 sm:grid-cols-2">{entries.map(([key, value]) => <div key={key} className="rounded border border-border/70 bg-muted/15 p-3"><div className="text-2xs uppercase tracking-wide text-muted-foreground">{key.replaceAll("_", " ")}</div><div className="mt-1 text-sm break-words">{typeof value === "object" ? JSON.stringify(value) : String(value)}</div></div>)}</div></div>{legacy.lead?.application_data ? <div><h2 className="text-sm font-semibold">Legacy application data</h2><pre className="mt-3 max-h-96 overflow-auto rounded-lg border border-border bg-muted/20 p-3 text-xs leading-5 text-muted-foreground">{JSON.stringify(legacy.lead.application_data, null, 2)}</pre></div> : null}</div>; }

function buildTimeline(record: RecordData): TimelineItem[] { const items: TimelineItem[] = []; for (const activity of record.crm_activities ?? []) items.push({ id: `crm-${activity.id}`, timestamp: activity.occurred_at, type: "crm", title: activity.title, body: activity.body, tone: "text-accent" }); for (const note of record.legacy?.notes ?? []) items.push({ id: `note-${note.id}`, timestamp: note.created_at, type: "note", title: `Legacy note${note.kind ? ` · ${note.kind}` : ""}`, body: note.body, tone: "text-foreground" }); for (const event of record.legacy?.events ?? []) items.push({ id: `event-${event.id}`, timestamp: event.occurred_at, type: "event", title: `Legacy event · ${event.event_type.replaceAll("_", " ")}`, body: event.payload && Object.keys(event.payload).length ? JSON.stringify(event.payload) : null, tone: "text-muted-foreground" }); for (const call of record.legacy?.calls ?? []) items.push({ id: `call-${call.id}`, timestamp: call.scheduled_for ?? call.created_at, type: "call", title: `Call · ${call.status}`, body: call.call_summary ?? (call.cash_collected_cents ? `Cash collected: ${currency(call.cash_collected_cents)}` : null), tone: call.closed ? "text-[color:var(--color-success)]" : "text-[color:var(--color-warning)]" }); return items.sort((a, b) => new Date(b.timestamp).getTime() - new Date(a.timestamp).getTime()); }
